#ifndef AKCPMBLOCKCODE_H_
#define AKCPMBLOCKCODE_H_

#include "robots/catoms3D/catoms3DBlockCode.h"
#include "comm/network.h"
#include "events/scheduler.h"
#include <vector>
#include <map>
#include <set>

namespace Catoms3D {

/*
 * ═══════════════════════════════════════════════════════════════════════════
 * AKC-PM Protocol Implementation
 * Based on: "A Lightweight Distributed Security Protocol with Adaptive 
 *            Key Management for Programmable Matter Based on Modular Robots"
 * Authors: Youssou Faye, Abdallah Makhoul, Serigne Mbacke Diene, Mohammed Ouzzif
 * ═══════════════════════════════════════════════════════════════════════════
 */

// ═══════════════════════════════════════════════════════════════════════════
// MESSAGE TYPES
// ═══════════════════════════════════════════════════════════════════════════

// Algorithm 1: Authentication for structure formation
static const int MSG_AUTH_REQUEST = 2001;     // SF-2: (links, n1, x||K0)
static const int MSG_KEY_CHALLENGE = 2002;    // SF-4: x1

// Algorithm 2: Authentication by proof of membership
static const int MSG_MEMBERSHIP_PROOF = 2003; // SF-2: (hops, x) or (hops, n1)
static const int MSG_MEMBERSHIP_KEY = 2004;   // SF-5: x1

// Control message
static const int MSG_STRUCTURE_READY = 2005;  // Signal that module is in structure

// ═══════════════════════════════════════════════════════════════════════════
// ENUMERATIONS
// ═══════════════════════════════════════════════════════════════════════════

// Security state of a module (Section VI)
enum SecurityState {
    STATE_UNLINKED,         // Not yet linked to the structure
    STATE_AUTHENTICATING,   // Authentication in progress
    STATE_AUTHENTICATED,    // Authenticated and linked to structure
    STATE_KEY_ESTABLISHED   // Shared key established
};

// Key management model (Section VI.A, VI.B - Figures 3, 4, 5)
enum KeyModel {
    SINGLE_KEY,   // Fig. 3: One key K1 for entire network
    FOUR_KEYS,    // Fig. 4: Four keys K1, K2, K3, K4
    MULTI_KEY     // Fig. 5: Multiple keys, one per link
};

// Authentication type (Figure 2)
enum AuthType {
    AUTH_IM_NM,   // (a) Initial module with new module
    AUTH_SM_NM,   // (b) Structure module with new module  
    AUTH_MI_MJ    // (c) Two modules already in structure (Algorithm 2)
};

// ═══════════════════════════════════════════════════════════════════════════
// SECURITY INFORMATION STRUCTURE
// ═══════════════════════════════════════════════════════════════════════════

struct SecurityInfo {
    SecurityState state;
    
    // Nonces (Section VI.A)
    uint64_t n0;              // Secret nonce, never disclosed
    uint64_t n1;              // n1 = H(n0), for sync verification
    uint64_t n2;              // Generated by structure module for key
    
    // Keys
    std::vector<uint8_t> K0;  // Authentication fingerprint K0 = H(L(n0 mod Nb))
    std::vector<uint8_t> K1;  // Shared key K1 = H(L(n2 mod Nb))
    
    // Structure info
    int linksInStructure;     // Number of authenticated links
    bool isInitialModule;     // True if this is the initial module (iM)
    
    SecurityInfo() : state(STATE_UNLINKED), n0(0), n1(0), n2(0),
                     linksInStructure(0), isInitialModule(false) {}
};

// ═══════════════════════════════════════════════════════════════════════════
// MAIN CLASS
// ═══════════════════════════════════════════════════════════════════════════

class AkcpmBlockCode : public Catoms3DBlockCode {
private:
    // Security information for this module
    SecurityInfo securityInfo;
    
    // Key management model
    KeyModel keyModel;
    
    // Protocol parameters (Section VII.B)
    static const int NB_CODE_LINES = 128;    // Number of lines in source code
    static const int LINE_SIZE_BITS = 256;   // Size of each line in bits
    static const int SYNC_DIVISOR = 10;      // Ts ≈ ts/10 (as per article)
    static const int SYNC_TOLERANCE = 5;     // ±5 tolerance (as per article Section VII.A)
    static const int TRANSMISSION_DELAY = 100; // Δt - transmission delay in µs
    
    // Neighbor management
    std::map<P2PNetworkInterface*, std::vector<uint8_t>> neighborKeys;  // Keys with neighbors
    std::map<P2PNetworkInterface*, bool> authenticatedNeighbors;        // Auth status
    std::map<P2PNetworkInterface*, bool> neighborsInStructure;          // Structure status
    std::set<P2PNetworkInterface*> pendingAuthentications;              // Pending auth
    
    // Nonce storage for ongoing authentications
    std::map<P2PNetworkInterface*, uint64_t> pendingN0;  // n0 used in pending auth
    
    // FOUR_KEYS model: track which key level to assign (1-4)
    int fourKeysCounter;  // Counts 1, 2, 3, 4, then resets to 1
    
    // Static: n2 for SINGLE_KEY model (shared by initial module)
    static uint64_t globalN2;
    static bool globalN2Set;

    // ═══════════════════════════════════════════════════════════════════════
    // CRYPTOGRAPHIC FUNCTIONS (Lightweight - Section I, VI)
    // ═══════════════════════════════════════════════════════════════════════
    
    // H() - One-way hash function (Table I)
    uint64_t H(uint64_t value);
    uint64_t H(const std::vector<uint8_t>& data);
    
    // L(i) - Get line i of source code (Section VI.A)
    std::vector<uint8_t> L(int lineNumber);
    
    // H(L(n mod Nb)) - Hash of code line (for K0, K1 generation)
    std::vector<uint8_t> HL(uint64_t n);
    
    // XOR operation (Table I)
    uint64_t XOR(uint64_t a, uint64_t b);
    
    // Concatenation for FOUR_KEYS model (128-bit operations)
    void concat128(uint64_t high, uint64_t low, uint64_t& outHigh, uint64_t& outLow);
    void xor128(uint64_t aHigh, uint64_t aLow, uint64_t bHigh, uint64_t bLow,
                uint64_t& outHigh, uint64_t& outLow);
    
    // Apply H() multiple times for FOUR_KEYS model
    uint64_t applyHashNTimes(uint64_t value, int n);
    
    // Generate random nonce
    uint64_t generateNonce();
    
    // ═══════════════════════════════════════════════════════════════════════
    // TIME SYNCHRONIZATION (Section VI.A, VII.A)
    // ═══════════════════════════════════════════════════════════════════════
    
    // Ts ≈ ts/10 - Approximate timestamp for sync
    uint64_t getTs();
    
    // Ts ≈ (Tr - Δt)/10 - Calculate Ts from reception time
    uint64_t calculateTs(uint64_t Tr, int deltaT);
    
    // ═══════════════════════════════════════════════════════════════════════
    // ALGORITHM 1: Authentication for structure formation (Section VI.A)
    // ═══════════════════════════════════════════════════════════════════════
    
    // SF-1, SF-2: New module initiates authentication
    void algorithm1_Initiate(P2PNetworkInterface* dest);
    
    // SF-3, SF-4: Structure module verifies and responds
    void algorithm1_Verify(P2PNetworkInterface* src, int links, uint64_t n1, 
                           uint64_t x, const std::vector<uint8_t>& K0);
    
    // SF-5: New module completes authentication
    void algorithm1_Complete(P2PNetworkInterface* src, uint64_t x1_high, 
                             uint64_t x1_low, int keyLevel);
    
    // ═══════════════════════════════════════════════════════════════════════
    // ALGORITHM 2: Authentication by proof of membership (Section VI.C)
    // ═══════════════════════════════════════════════════════════════════════
    
    // SF-1, SF-2: Module initiates membership proof
    void algorithm2_Initiate(P2PNetworkInterface* targetModule, 
                             P2PNetworkInterface* commonNeighbor);
    
    // SF-3: Propagate membership proof
    void algorithm2_Propagate(P2PNetworkInterface* src, int hops, uint64_t xOrN1);
    
    // SF-5, SF-6: Complete membership proof authentication
    void algorithm2_Complete(P2PNetworkInterface* src, uint64_t x1);
    
    // ═══════════════════════════════════════════════════════════════════════
    // STRUCTURE MANAGEMENT
    // ═══════════════════════════════════════════════════════════════════════
    
    void notifyNeighborsStructureReady();
    void checkNewNeighbors();
    int countConnectedNeighbors();
    bool hasCommonNeighborInStructure(P2PNetworkInterface* target);

public:
    AkcpmBlockCode(Catoms3DBlock *host);
    ~AkcpmBlockCode() override;
    
    static BlockCode* buildNewBlockCode(BuildingBlock *host) {
        return new AkcpmBlockCode((Catoms3DBlock*)host);
    }
    
    // ═══════════════════════════════════════════════════════════════════════
    // MESSAGE HANDLERS
    // ═══════════════════════════════════════════════════════════════════════
    
    void onAuthRequestReceived(std::shared_ptr<Message> msg, P2PNetworkInterface* src);
    void onKeyChallengeReceived(std::shared_ptr<Message> msg, P2PNetworkInterface* src);
    void onMembershipProofReceived(std::shared_ptr<Message> msg, P2PNetworkInterface* src);
    void onMembershipKeyReceived(std::shared_ptr<Message> msg, P2PNetworkInterface* src);
    void onStructureReadyReceived(std::shared_ptr<Message> msg, P2PNetworkInterface* src);
    
    // ═══════════════════════════════════════════════════════════════════════
    // LIFECYCLE EVENTS
    // ═══════════════════════════════════════════════════════════════════════
    
    void startup() override;
    void processLocalEvent(EventPtr pev) override;
    void onMotionEnd() override;
    void onTap(int face) override;
    
    // ═══════════════════════════════════════════════════════════════════════
    // STATE QUERIES
    // ═══════════════════════════════════════════════════════════════════════
    
    bool isInStructure() const;
    bool isInitialModule() const { return securityInfo.isInitialModule; }
    SecurityState getState() const { return securityInfo.state; }
    int getLinksInStructure() const { return securityInfo.linksInStructure; }
    
    // Configuration
    void setAsInitialModule();
    void setKeyModel(KeyModel model) { keyModel = model; }
};

// ═══════════════════════════════════════════════════════════════════════════
// MESSAGE CLASSES
// ═══════════════════════════════════════════════════════════════════════════

// Algorithm 1, SF-2: Authentication Request (links, n1, x||K0)
class AuthRequestMessage : public Message {
public:
    int links;                  // Number of links in structure (1 = not yet linked)
    uint64_t n1;                // n1 = H(n0) for sync verification
    uint64_t x;                 // x = Ts ⊕ n0 (protected nonce)
    std::vector<uint8_t> K0;    // K0 = H(L(n0 mod Nb)) authentication fingerprint
    
    AuthRequestMessage(int _links, uint64_t _n1, uint64_t _x, 
                       const std::vector<uint8_t>& _K0);
    ~AuthRequestMessage() override;
};

// Algorithm 1, SF-4: Key Challenge (x1)
// For SINGLE_KEY: x1 = n2 ⊕ n0 (64-bit)
// For FOUR_KEYS: x1 = (H^(k-1)(n2) || n2) ⊕ (n0 || n0) (128-bit)
class KeyChallengeMessage : public Message {
public:
    uint64_t x1_high;           // High 64 bits (or 0 for SINGLE_KEY)
    uint64_t x1_low;            // Low 64 bits (= x1 for SINGLE_KEY)
    int keyLevel;               // Key level for FOUR_KEYS (1-4), 0 for SINGLE_KEY
    
    KeyChallengeMessage(uint64_t _x1);  // Constructor for SINGLE_KEY
    KeyChallengeMessage(uint64_t _x1_high, uint64_t _x1_low, int _keyLevel);  // FOUR_KEYS
    ~KeyChallengeMessage() override;
};

// Algorithm 2, SF-2/SF-3: Membership Proof
class MembershipProofMessage : public Message {
public:
    int hops;                   // Remaining hops (decremented at each hop)
    uint64_t value;             // x = K1 ⊕ n0 (to neighbor) or n1 (to target)
    bool isN1;                  // true if value is n1, false if value is x
    
    MembershipProofMessage(int _hops, uint64_t _value, bool _isN1);
    ~MembershipProofMessage() override;
};

// Algorithm 2, SF-5: Membership Key
class MembershipKeyMessage : public Message {
public:
    uint64_t x1;                // x1 = K2 ⊕ n0
    
    MembershipKeyMessage(uint64_t _x1);
    ~MembershipKeyMessage() override;
};

// Structure Ready notification
class StructureReadyMessage : public Message {
public:
    StructureReadyMessage();
    ~StructureReadyMessage() override;
};

} // namespace Catoms3D

#endif /* AKCPMBLOCKCODE_H_ */
